In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt

In [2]:
x = torch.ones(4,9,3,10)
y = torch.ones(3,10,12)

In [8]:
torch.Tensor(1, 3*4).shape

torch.Size([1, 12])

In [73]:
(y.unsqueeze(-1)/z[None, None, :])

tensor([[[    nan,  0.0000,  0.0000,  0.0000,  0.0000],
         [    inf, 16.0000,  8.0000,  5.3333,  4.0000],
         [    inf, 32.0000, 16.0000, 10.6667,  8.0000]],

        [[    inf,  4.0000,  2.0000,  1.3333,  1.0000],
         [    inf, 20.0000, 10.0000,  6.6667,  5.0000],
         [    inf, 36.0000, 18.0000, 12.0000,  9.0000]],

        [[    inf,  8.0000,  4.0000,  2.6667,  2.0000],
         [    inf, 24.0000, 12.0000,  8.0000,  6.0000],
         [    inf, 40.0000, 20.0000, 13.3333, 10.0000]],

        [[    inf, 12.0000,  6.0000,  4.0000,  3.0000],
         [    inf, 28.0000, 14.0000,  9.3333,  7.0000],
         [    inf, 44.0000, 22.0000, 14.6667, 11.0000]]])

In [47]:
adj = torch.eye(3)
edge_idx = adj.nonzero().T
adj[edge_idx[0], edge_idx[1]]

tensor([1., 1., 1.])

In [16]:
torch.repeat_interleave(x, 4, dim=-1)

tensor([[[ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,
           4,  4,  4],
         [ 5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,
           9,  9,  9],
         [10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14,
          14, 14, 14],
         [15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19,
          19, 19, 19]],

        [[20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24,
          24, 24, 24],
         [25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 28, 28, 28, 28, 29,
          29, 29, 29],
         [30, 30, 30, 30, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 34,
          34, 34, 34],
         [35, 35, 35, 35, 36, 36, 36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 39,
          39, 39, 39]],

        [[40, 40, 40, 40, 41, 41, 41, 41, 42, 42, 42, 42, 43, 43, 43, 43, 44,
          44, 44, 44],
         [45, 45, 45, 45, 46, 46, 46, 46, 47, 47, 47, 47, 48, 48, 48, 48, 49,
         