In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt

In [14]:
x = torch.ones(2, 3, 4, 5)
y = torch.ones(2, 3, 4) * 2
z = torch.ones(2, 3, 1, 5) * 3

In [10]:
x = torch.Tensor([[4, 2, 1, 3],
                  [1, 2, 3, 4]])

In [32]:
torch.argsort(x)

tensor([[2, 1, 3, 0],
        [0, 1, 2, 3]])

In [31]:
idxs = torch.argsort(x)[:, :2]
idxs

tensor([[2, 1],
        [0, 1]])

In [29]:
y = torch.zeros_like(x).scatter(1, idxs, 1)


tensor([[0., 1., 1., 0.],
        [1., 1., 0., 0.]])

In [11]:
 fisw.unsqueeze(-1).shape

torch.Size([2, 3, 4, 4, 1])

In [47]:
adj = torch.eye(3)
edge_idx = adj.nonzero().T
adj[edge_idx[0], edge_idx[1]]

tensor([1., 1., 1.])

In [16]:
torch.repeat_interleave(x, 4, dim=-1)

tensor([[[ 0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3,  4,
           4,  4,  4],
         [ 5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,
           9,  9,  9],
         [10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14,
          14, 14, 14],
         [15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19,
          19, 19, 19]],

        [[20, 20, 20, 20, 21, 21, 21, 21, 22, 22, 22, 22, 23, 23, 23, 23, 24,
          24, 24, 24],
         [25, 25, 25, 25, 26, 26, 26, 26, 27, 27, 27, 27, 28, 28, 28, 28, 29,
          29, 29, 29],
         [30, 30, 30, 30, 31, 31, 31, 31, 32, 32, 32, 32, 33, 33, 33, 33, 34,
          34, 34, 34],
         [35, 35, 35, 35, 36, 36, 36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 39,
          39, 39, 39]],

        [[40, 40, 40, 40, 41, 41, 41, 41, 42, 42, 42, 42, 43, 43, 43, 43, 44,
          44, 44, 44],
         [45, 45, 45, 45, 46, 46, 46, 46, 47, 47, 47, 47, 48, 48, 48, 48, 49,
         